openapi: 3.0.2
info:
  version: '1.0.0'
  
  title: Python Wordle
  
  description: 'API Spec for Python Wordle'
externalDocs:
  description: Github Repository Link 
  url: 'https://github.com/alexchung1233/Wordle-Python'

tags:
  - name: Game
    description: Operations about user
  - name: User
    description: Operations about a game
  - name: Dictionary
    description: Operations about for the dictionary
servers:
  - url: 'http://3.19.243.218:80/v1/wordle'

paths:
  '/wordle/user/{user_id}': # path parameter in curly braces

    # parameters list that are used with each operation for this path
    parameters:
      - name: user_id
        in: query
        description: User id
        schema:
          type: string
    get: # documentation for GET operation for this path
      tags:
        - User
      
      # summary is up to 120 symbold but we recommend to be shortest as possible
      summary: Get user by user id
            
      # list of parameters for the operation
      parameters:
        - name: user_id
          in: path
          description: The user associated
          required: true
          schema:
            type: string
      responses: # list of responses
        '200':
          description: Success
          content:
            application/json: # operation response mime type
              schema: # response schema can be specified for each response
                $ref: '#/components/schemas/User'
              example: # response example
                user_id: 543d11b9-6850-4bdb-9b0f-7962e9a2b037
                user_name: John Doe
        '404':
          description: User not found
  /wordle/user/{user_id}/games:
    get:
      tags:
        - User
      summary: Create a game
      parameters:
        - name: user_id
          in: path
          description: The user associated
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json: # operation response mime type
              schema: # response schema can be specified for each response
                $ref: '#/components/schemas/GameList'
              example: # response example
                games: [{"game_id": "06d05ecd-310b-4a79-9dea-6d5f115eb2b9", "user_id": "543d11b9-6850-4bdb-9b0f-7962e9a2b037","user_name": "Alex Chungs", "answer": "account", "max_attempts": 8, "current_attempts": 0, "attempts": []},{"game_id": "1dbc72c5-d4fb-43b3-b87d-0e02d9123a64", "user_id": "543d11b9-6850-4bdb-9b0f-7962e9a2b037", "user_name":"Alex Chungs", "answer": "signing", "max_attempts": 8, "current_attempts": 0, "attempts": []}]
  
  /wordle/game: # path parameter in curly braces
    post: # documentation for POST operation for this path
      tags:
        - Game
      summary: Create a game
      responses:
        '201':
          description: Created
          content:
            application/json: # operation response mime type
              schema: # response schema can be specified for each response
                $ref: '#/components/schemas/Game'
      requestBody:
        content:
          application/json: # operation response mime type
            schema: # response schema can be specified for each response
              $ref: '#/components/schemas/CreateGamePayload'
        required: true
  /wordle/game/{game_id}: # path parameter in curly braces
    get:
      tags:
        - Game
      summary: Get a game
      responses:
        '200':
          description: Ok
          content:
            application/json: # operation response mime type
              schema: # response schema can be specified for each response
                $ref: '#/components/schemas/Game'
  

  /wordle/game/{game_id}/attempt:
    post:
      tags:
        - Game
      summary: Echo test
      description: Receive the exact message you've sent
      responses:
        '201':
          description: Created
          content:
            application/json: # operation response mime type
              schema: # response schema can be specified for each response
                $ref: '#/components/schemas/Game'
      requestBody:
        content:
          application/json: # operation response mime type
            schema: # response schema can be specified for each response
              $ref: '#/components/schemas/AttemptPayload'
        required: true
  /wordle/dictionary:
    post:
      tags:
        - Dictionary
      summary: Echo test
      description: Receive the exact message you've sent
      responses:
        '201':
          description: New word created
          content:
            application/json:
              schema:
                type: string
              examples:
                response:
                  value: New word added successfully
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: string
              examples:
                response:
                  value: Word already edxisys
      requestBody:
        content:
          application/json: # operation response mime type
            schema: # response schema can be specified for each response
              $ref: '#/components/schemas/NewWordPayload'
        required: true

components:
  schemas:
    GameList:
      type: object
      properties:
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'
    CreateGamePayload:
      type: object
      properties:
        user_name:
          type: string
        answer_length:
          type: integer
        user_id:
          type: string
    Game:
      type: object
      properties:
        game_id:
          type: string
        user_id:
          type: string
        user_name: 
          type: string
        max_attempts:
          type: string
        attempts:
          type: array
        current_attempts:
          type: integer
    User:
      type: object
      properties:
        user_name:
          description: User supplied username
          type: string
        user_id:
          type: string
    AttemptPayload:
      type: object
      properties:
        attempt_word: 
          description: Attempt word
          type: string
    NewWordPayload:
      type: object
      properties:
        word:
          type: string